const urlScreenPhone = [
    '/thay-man-hinh-iphone-6',
    '/thay-man-hinh-iphone-6s',
    '/thay-man-hinh-iphone-6s-plus',
    '/thay-man-hinh-iphone-7',
    '/thay-man-hinh-iphone-7-plus',
    '/thay-man-hinh-iphone-8',
    '/thay-man-hinh-iphone-8-plus',
    '/thay-man-hinh-iphone-x',
    '/thay-man-hinh-iphone-xs-max',
    '/thay-man-hinh-iphone-11',
    '/thay-man-hinh-iphone-11-pro-max',
    '/thay-man-hinh-iphone-12',
    '/thay-man-hinh-iphone-12-pro-max',
    '/thay-man-hinh-iphone-13',
    '/thay-man-hinh-iphone-13-pro-max',
    '/thay-man-hinh-samsung-galaxy-s20',
    '/thay-man-hinh-samsung-galaxy-s20-ultra',
    '/thay-man-hinh-samsung-galaxy-s21',
    '/thay-man-hinh-samsung-galaxy-s21-ultra',
    '/thay-man-hinh-samsung-galaxy-a30',
    '/thay-man-hinh-samsung-galaxy-a50',
    '/thay-man-hinh-samsung-galaxy-a70',
    '/thay-man-hinh-xiaomi-redmi-note-7',
    '/thay-man-hinh-xiaomi-redmi-note-8',
    '/thay-man-hinh-xiaomi-redmi-note-10-pro',
    '/thay-man-hinh-xiaomi-redmi-k20',
    '/thay-man-hinh-pocophone-f1'
];

const urlCameraPhone = [
    '/thay-camera-sau-iphone-6',
    '/thay-camera-sau-iphone-6s',
    '/thay-camera-sau-iphone-6s-plus',
    '/thay-camera-sau-iphone-7',
    '/thay-camera-sau-iphone-7-plus',
    '/thay-camera-sau-iphone-8',
    '/thay-camera-sau-iphone-8-plus',
    '/thay-camera-sau-iphone-x',
    '/thay-camera-sau-iphone-xs-max',
    '/thay-camera-sau-iphone-11',
    '/thay-camera-sau-iphone-11-pro-max',
    '/thay-camera-sau-iphone-12',
    '/thay-camera-sau-iphone-12-pro-max',
    '/thay-camera-sau-iphone-13',
    '/thay-camera-sau-iphone-13-pro-max',
    '/thay-camera-sau-samsung-galaxy-s20-ultra',
    '/thay-camera-sau-samsung-galaxy-s21',
    '/thay-camera-sau-samsung-galaxy-s21-ultra',
    '/thay-camera-sau-samsung-galaxy-a30',
    '/thay-camera-sau-samsung-galaxy-a50',
    '/thay-camera-sau-samsung-galaxy-a70'
];


